version: '3'
services:
  cargo:
    build: .
    image: helium/cargo:latest
    container_name: helium_cargo
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_DB=cargo_elixir
      - DATABASE_HOST=postgres
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: helium_postgres
    environment:
        - POSTGRES_DB=cargo_elixir
        - POSTGRES_PASSWORD=postgres
    restart: always
