version: '3'
services:
  cargo:
    build: .
    image: helium/cargo:latest
    container_name: helium_cargo
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: helium_postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    restart: always